Repository CMC-16th-TeamU/backend, pull requests merged in 2024-11, with the labels that each got.

#2 [Deploy] Github Actions CI/CD 구현
  .github/workflows/mzregret_dev.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/project/backend/BackendApplication.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🌏 Deploy

#4 [Feature] Entity 생성
  docker-compose.yml
  src/main/java/project/backend/domain/BaseEntity.java
  src/main/java/project/backend/domain/detailgoal/DetailGoal.java
  src/main/java/project/backend/domain/goal/Goal.java
  src/main/java/project/backend/domain/regret/Regret.java
  src/main/java/project/backend/domain/remindmessage/RemindMessage.java
  src/main/java/project/backend/domain/user/User.java
Labels: 🌏 Deploy

#17 [Feature] 응답 통일 구현
  src/main/java/project/backend/api/ApiResponse.java
  src/main/java/project/backend/api/GlobalExceptionHandler.java
  src/main/java/project/backend/exception/BusinessException.java
  src/main/java/project/backend/exception/ErrorCode.java
  src/main/java/project/backend/exception/ErrorResponse.java
Labels: ✨ Feature

#29 [Refactor] user_id 전달 방식 통일
  build.gradle
  src/main/java/project/backend/api/filtering/FilteringController.java
  src/main/java/project/backend/api/regret/RegretController.java
  src/main/java/project/backend/api/regret/request/UserRegretRequest.java
  src/main/java/project/backend/api/user/UserController.java
  src/main/java/project/backend/api/user/request/UserUpdateRequest.java
  src/main/java/project/backend/application/filtering/FilteringService.java
  src/main/java/project/backend/application/filtering/request/FilterOptionsDto.java
  src/main/java/project/backend/application/filtering/response/RegretsDto.java
  src/main/java/project/backend/application/filtering/response/RegretsListDto.java
  src/main/java/project/backend/application/regret/RegretService.java
  src/main/java/project/backend/application/regret/response/UserRegretListResponse.java
  src/main/java/project/backend/application/regret/response/UserRegretResponse.java
  src/main/java/project/backend/application/regret/response/dto/UserRegretDto.java
  src/main/java/project/backend/application/user/UserService.java
  src/main/java/project/backend/application/user/request/UserInfoDto.java
  src/main/java/project/backend/domain/regret/repository/RegretRepository.java
  src/main/java/project/backend/domain/user/User.java
Labels: 🔨 Refactor

#34 [Refactor] GetMapping user_id 전달 방식 변경
  build.gradle
  src/main/java/project/backend/api/regret/RegretController.java
  src/main/java/project/backend/api/regret/request/UserRegretRequest.java
  src/main/java/project/backend/application/regret/RegretService.java
  src/main/java/project/backend/config/SwaggerConfig.java
Labels: 🔨 Refactor

#36 [Refactor] filtering을 regret으로 병합
  src/main/java/project/backend/api/filtering/FilteringController.java
  src/main/java/project/backend/api/regret/RegretController.java
  src/main/java/project/backend/application/filtering/FilteringService.java
  src/main/java/project/backend/application/filtering/response/RegretsDto.java
  src/main/java/project/backend/application/filtering/response/RegretsListDto.java
  src/main/java/project/backend/application/regret/RegretService.java
  src/main/java/project/backend/application/regret/request/FilterOptionsDto.java
  src/main/java/project/backend/domain/regret/repository/RegretRepository.java
Labels: 🔨 Refactor

#37 [Refactor] Filtering 구조 변경
  src/main/java/project/backend/api/GlobalExceptionHandler.java
  src/main/java/project/backend/api/regret/RegretController.java
  src/main/java/project/backend/api/regret/request/RegretFilterRequest.java
  src/main/java/project/backend/application/regret/RegretService.java
  src/main/java/project/backend/application/regret/request/RegretFilterServiceRequest.java
Labels: 🔨 Refactor
